### ISSUE TITLE
希望将所有翻译好的视频整理成一个B站合集

### ISSUE THREAD

**Issue by Deardrops** [1c7/Crash-Course-Computer-Science-Chinese#1]
方便下载
感谢翻译，辛苦了！

**Comment by 1c7** [comment]
我们有打算做成 B 站合集。过阵子我们会从第1集到第40集做一次精校。然后把精校版做合集。

**Comment by vc1** [comment]
@1c7 提供单独的字幕下载吗，还有多传几个平台，或者视频文件放网盘

**Comment by 1c7** [comment]
@vc1 
1. 是否提供字幕下载：不提供字幕下载（比如 ass 字幕格式），理由这里就不赘述了
2. 多传几个平台：除了 B 站，我试过 A 站，A 站莫名不过审，其他站不清楚有什么好的，就没传
3. 网盘有：https://pan.baidu.com/s/1gJvKsM9hJexBmMbWwvGHKg

**Comment by vc1** [comment]
@1c7 爱奇艺优酷等等，手机套餐能免流

**Comment by 1c7** [comment]
@vc1 这样嗯。最近网易公开课要上这个，我传给它们了。
爱奇艺和优酷的话我看看情况。毕竟不是随便注册一个号随便一扔就行。方便的话可能会放过去~
感谢建议~
