### ISSUE TITLE
Are you guys interested in making up some excercises?

### ISSUE THREAD

**Issue by ytdu** [1c7/Crash-Course-Computer-Science-Chinese#12]
课程很不错，但感觉缺少练习会像流水账一样看过就忘。

咱们一起针对每个视频出一套习题吧。

**Comment by 1c7** [comment]
### 字幕组Q群: 305631757
可以加进来和其他人讨论。我个人对这个提议没啥兴趣

### 对这个提议没兴趣的具体理由如下：
1. 我没这个能力
2. 我没这个意愿

这个系列的定位是"入门"课，8个小时长度说短也不短，内容把各个话题都简单摸了一下。
看完了就该接着看别的。而不是一直在这上面死磕。
这系列是给"没有编程基础的人"看的。

大概的顺序应该是：
(1)看这个系列简单入门 -> (2)学个语言比如 Python -> (3)做点东西或者再学学 HTML,CSS,JS 做点 Web 的东西有点成就感 -> (4)再根据个人情况继续深入学习

你说的习题大概在 (2) 和 (3) 的范围。
属于下一步的东西。

**Comment by 1c7** [comment]
主要还是你给的信息太少了，我只能依据现有信息判断。

那么我追问几个问题：

1. (目的) 这套习题的最终目的是什么？只是加深记忆？有没有别的？
2. (数量) 这套习题大概有多少个？简单举个例子，第一集和最后一集基本泛泛而谈，第25集个人电脑更是塞满了历史。所以习题个数肯定 < 40 个。最终数量大概在20~30个。
3. (形式) 习题的形式是？单选+多选+个别不到40行的编程题混搭？
4. (放哪里?) 习题放在哪里？做个网站？最终形式就像考试一样？
5. 谁来研发这套习题？谁来定题目和答案？
6. 所有这些东西的成本谁来承担？
7. 习题是否收费？

**Comment by 1c7** [comment]
我们字幕组是以爱好形式做的（在中国翻译很不值钱的，我简单算过如果做成盈利字幕组，赚那几个钱不但累得要死而且还很少，我做程序员怎么着都比做翻译赚钱）

如果搞了一套收费的配套习题。会给人感觉恰烂钱。这就搞得很不舒服了。

**Comment by 1c7** [comment]
### 简而言之
你做什么都可以，    

但字幕组不会用名誉给你们的产品背书。不管你们的产品是收费的还是免费的。
我们会把中字视频保持独立。不和其他东西进行捆绑宣传。
我们不会在B站或者微博宣传说"这里有一个配套的习题 blah blah"。

最多就是你在评论区留言一个 "Hello 大家好，我和一群志愿者们针对视频做了配套的免费习题：https://xxx 有兴趣的朋友可以来看一下"
