### ISSUE TITLE
第四集翻译有点小错误

### ISSUE THREAD

**Issue by w-g-b** [1c7/Crash-Course-Computer-Science-Chinese#2]
## 4. 二进制-Representing Numbers and Letters with Binary
* 具体时间   05:30
* quintillion有道上的翻译为：百万的三次方（美、法）；百万的五次方（英、德）
* 按照这里的情景应该是前者，所以应该翻译为9.2*10^18

**Comment by 1c7** [comment]
@w-g-b 好，感谢报错。
我仔细看看是对是错。

时间预计：
查询 + 修改字幕 + 压制视频 + 上传视频 + 过B站审。
预计是1-2天吧，如果工作耽误了可能会再多几天。

**Comment by 1c7** [comment]
### 谷歌搜索 quintillion
https://www.google.com/search?q=quintillion&ie=utf-8&oe=utf-8&aq=t

图片1：
![image](https://user-images.githubusercontent.com/1804755/40404088-8531d124-5e88-11e8-9d27-e4adbd1a8d92.png)

图片2：
https://www.merriam-webster.com/dictionary/quintillion
![image](https://user-images.githubusercontent.com/1804755/40404116-ad93bf56-5e88-11e8-9da2-b32ba5f96fe5.png)

图片3：
http://www.dictionary.com/browse/quintillion
![image](https://user-images.githubusercontent.com/1804755/40404120-b71432fe-5e88-11e8-9ca3-a498ec4142e3.png)

**Comment by 1c7** [comment]
图片4：http://www.dictionary.com/browse/quintillion

![image](https://user-images.githubusercontent.com/1804755/40404134-c9ffc31a-5e88-11e8-9ba6-727a5450bf87.png)

**Comment by 1c7** [comment]
图片5：https://en.wiktionary.org/wiki/quintillion
![image](https://user-images.githubusercontent.com/1804755/40404153-e590225a-5e88-11e8-9fbe-2e6a03de7b5e.png)

**Comment by 1c7** [comment]
## 结论
quintillion 的确是 10^18。
字幕错了。

开始修复。
感谢纠错~

**Comment by 1c7** [comment]
老实说我蛮奇怪怎么我们翻译和校对的时候都没揪出来这个错。。
反正我是总负责人。我的锅（接下）

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/40404337-d73d0f28-5e89-11e8-8522-871727f0da3f.png)

**Comment by 1c7** [comment]
谷歌搜索『64 bit number max』

https://www.google.com/search?biw=1680&bih=976&ei=6fYEW6iYGIX6vATa0KmADg&q=64+bit+number+max&oq=64+bit+number+max&gs_l=psy-ab.3...5036.7946.0.8108.17.9.0.0.0.0.0.0..0.0....0...1c.1j4.64.psy-ab..17.0.0....0.innbP-IYg8Q

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/40404436-6fb1430a-5e8a-11e8-81d7-b570d9d4c0be.png)

**Comment by 1c7** [comment]
问题已修复。第4集于2018-5-23 的 15:52 通过审核。
此 issue 关闭
