### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 1c7** [1c7/Crash-Course-Computer-Science-Chinese#20]
![image](https://user-images.githubusercontent.com/1804755/100831238-53c89c80-34a0-11eb-8b94-c4385758467f.png)

**Comment by ichengzi** [comment]
用软件抽象硬件， 提供给应用软件API， 这个翻译很对呀。

**Comment by 1c7** [comment]
好勒，一直没空看前后文，先关了这个 issue
