### ISSUE TITLE
一点点小建议

### ISSUE THREAD

**Issue by w-g-b** [1c7/Crash-Course-Computer-Science-Chinese#5]
能否把每一集最前面的重点内容整理出来放到github上，总结的很好。
这样要看某一部分的内容就不用每次都跳到视频最前面去找了，也不用每个视频都开一遍，方便查阅。
<img width="668" alt="image" src="https://user-images.githubusercontent.com/23725154/41115312-b5a47ec8-6ab9-11e8-8cfb-944e06e597d8.png">

**Comment by 1c7** [comment]
嗯，好~ 我这几天整理一下，放到 README 里

**Comment by 1c7** [comment]
感谢建议~

**Comment by 1c7** [comment]
已搞定。 放到了 README 的底部。

![image](https://user-images.githubusercontent.com/1804755/41122741-151a3252-6acf-11e8-9967-75577862d78c.png)

**Comment by 1c7** [comment]
这些信息是写了个 node.js 脚本直接从 ass 字幕文件中抽取出来。不是手动复制黏贴的。

loop 当前目录所有 ass 字幕然后抽取特定 style 的字幕出来本应该20分钟搞定。
然而从2点多写到3点多…… 无语…（深夜吐槽

那些代码也 push 上来了

![image](https://user-images.githubusercontent.com/1804755/41122885-8a900a2a-6acf-11e8-8558-672b2b150e70.png)

纯粹是做个备份。其他人没有 ass 字幕文件也没法跑这个

**Comment by w-g-b** [comment]
赞赞赞
