### ISSUE TITLE
鸡蛋里挑骨头吧，错了一个字母

### ISSUE THREAD

**Issue by AHBICJ** [1c7/Crash-Course-Computer-Science-Chinese#9]
第九集01：50这里错了一个字母 中文里 应该是 SSE
![WSSEBX@{891F%VQLLBGBHO1](https://user-images.githubusercontent.com/31472450/59258655-f49f1880-8c6a-11e9-8c45-cdc241f5c166.png)
git上修一下吧，B站也没有必要重新压重新传
另外感谢字幕组的默默奉献呐
:+1::thumbsup::heart:

**Comment by 1c7** [comment]
https://github.com/1c7/Crash-Course-Computer-Science-Chinese/commit/6563d8448915d17ab5ed35031538e0b712bd0a5a
Fixed

**Comment by 1c7** [comment]
感谢抓虫，不算鸡蛋里挑骨头，的确是错了。
B站我的确懒得再压制了…不管了，小问题。
感谢
